### ISSUE TITLE
Can anyone suggest what version of tensorflow is being used in background 

### ISSUE THREAD

**Issue by palbha** [keras-rl/keras-rl#344]
Using version -- 
import keras ; keras.__version__
Out[92]: '2.3.1'

import tensorflow as tf; print(tf.__version__)
2.0.0
facing erros like the below and unable to run keras-rl example on ggogle colab as well as on jupyter --
    if isinstance(x, ops.Tensor):

AttributeError: module 'tensorflow.python.framework.common_shapes' has no attribute 'rank'

**Comment by Dr-Tuski** [comment]
There are the versions I use:
Python: 3.6 or 3.7
Keras: 2.3.1 or 2.2.4
TensorFlow: 1.13.1

I wonder if tensorflow 2.0 can work. Maybe try it next time.

I hope this information can help you.

**Comment by palbha** [comment]
TypeError: len is not well defined for symbolic Tensors. (activation_20/Identity:0) Please call `x.shape` rather than `len(x)` for shape information.

 getting this issue even I updated the tensorflow as you are using

**Comment by Dr-Tuski** [comment]
> 
> 
> TypeError: len is not well defined for symbolic Tensors. (activation_20/Identity:0) Please call `x.shape` rather than `len(x)` for shape information.
> 
> getting this issue even I updated the tensorflow as you are using

I got the same issue on another computer, then I used Python 3.6 and it works.
Maybe Python 3.6 can work.

**Comment by TheTrash** [comment]
I solved the issue downgrading numpy to 1.16.4

The other version are
keras on 2.3.1
tensorflow on 2.0.0-beta1
python on 3.7.5 but i see that keras isn't compatibile with python 3.7 but i'm using it
All of this things have a crazy compatibility each others

**Comment by toksis** [comment]
There is a Keras-rl2 for Tensor flow2. Not sure if it is being updated.

**Comment by yingshaoxo** [comment]
According to my test, it's only working by using `import keras` right now.

Use `tensorflow.keras` will cause a lot of bugs.

**Comment by liuminxing** [comment]
i have keras 2.3.1 and the rl works with tensorflow 1.13.1.
Recently i update the version of tensorflow to 2.0 and there are some erro raised.
I decide to downgrade the tensorlow again.

**Comment by cboettig** [comment]
Yes, I believe you need tensorflow 1.x for this module.

**Comment by palbha** [comment]
Thanks for your suggestions

**Comment by nixklai** [comment]
To those of you who found this thread because the `len is not well defined for symbolic Tensors` error, the following should be the lastest usable Tensorflow and Keras version are `1.13.2` and `2.3.0`.
